site_name: -{{ REPO_NAME }}-
site_url: https://psmodule.io/-{{ REPO_NAME }}-
repo_name: -{{ REPO_OWNER }}-/-{{ REPO_NAME }}-
repo_url: https://github.com/-{{ REPO_OWNER }}-/-{{ REPO_NAME }}-

theme:
  name: material
  language: en
  logo: Assets/icon.png
  favicon: Assets/icon.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jedJWCPAhD
      name: PSModule on Discord
    - icon: fontawesome/brands/github
      link: https://github.com/PSModule/
      name: PSModule on GitHub
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
